### Repaso Numpy

In [1]:
import numpy as np


In [2]:
numeros = [1,2,3]
array = np.array(numeros)

In [3]:
array

array([1, 2, 3])

In [4]:
type(array)

numpy.ndarray

In [5]:
#Generamos numeros
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.arange(0,30,2) #CON PASOS

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
np.zeros(15) #15 elementos de ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10) #10 elementos de unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#tambien se pueden hacer matrices
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#generamos numeros en base a un rango y dividido segun un valor
np.linspace(0,30,5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [29]:
#generamos numeros randomicos en base a un rango
np.random.randint(0,100,6)

array([84, 89, 25, 80, 57, 11])

In [37]:
#podemos crear arrays con numeros aleatorios dentro, de esta manera
array = np.random.randint(0,100,6)

In [38]:
array

array([ 1, 52, 30, 35, 84, 48])

In [39]:
#obtenemos el valor maximo
array.max()

84

In [40]:
#obtenemos el valor minimo
array.min()

1

In [41]:
#obtenemos la media
array.mean()

41.666666666666664

In [42]:
#modificamos la dimension
array = array.reshape(2,3)

In [43]:
array

array([[ 1, 52, 30],
       [35, 84, 48]])

In [44]:
#para obtener el 35
array[1][0]

35

In [50]:
#para obtener valores mayores que 30
filtro = array > 30
#fitlro devuelve valores booleanos
filtro


array([[False,  True, False],
       [ True,  True,  True]])

In [52]:
array2 = array[filtro]

In [53]:
array2

array([52, 35, 84, 48])