# Red Neuronal

In [21]:
import tensorflow as tf
import numpy as np

In [22]:
aleatorio_atorio_a = np.random.uniform(0,50,(4,4)) #matriz cn valores de 0 a 50 en una matriz de 4x4

In [23]:
aleatorio_a

array([[29.98882788, 36.51949758, 26.97035657, 37.40358269],
       [49.68791888, 45.41008907, 39.12293284,  0.91895602],
       [ 5.54079127,  3.30240546, 12.48533328,  3.4199975 ],
       [48.81546756, 41.50852728, 39.52490057, 35.17213839]])

In [24]:
aleatorio_b = np.random.uniform(0,50,(4,1))

In [25]:
aleatorio_b

array([[21.47460262],
       [43.13164743],
       [13.02832864],
       [ 2.52675019]])

In [26]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [27]:
suma = a + b 
mul = a * b

In [28]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma,feed_dict={a:10,b:20})
    print(resultado_suma)

30.0


In [29]:
with tf.Session() as sesion:
    resultado = sesion.run(suma,feed_dict={a:aleatorio_a,b:aleatorio_b})
    print(resultado)

[[51.463432 57.9941   48.444958 58.878185]
 [92.819565 88.54173  82.25458  44.050606]
 [18.56912  16.330734 25.513662 16.448326]
 [51.342216 44.035275 42.05165  37.698887]]


In [31]:
with tf.Session() as sesion:
    resultado = sesion.run(mul, feed_dict={a:aleatorio_a,b:aleatorio_b})
    print(resultado)

[[ 643.99817   784.24164   579.1777    803.22705 ]
 [2143.1218   1958.6119   1687.4366     39.63609 ]
 [  72.187256   43.024822  162.66302    44.55685 ]
 [ 123.34449   104.88167    99.86955    88.8712  ]]


## Ejemplo de Red Neuronal

In [32]:
caracteristicas = 10
neuronas = 4

In [33]:
x = tf.placeholder(tf.float32,(None,caracteristicas)) #no se conoce el numero de pruebas que hay (filas), pero si las caracteristicas (columnas)

In [38]:
W= tf.Variable(tf.random.normal([caracteristicas,neuronas])) #el tamaño que tiene es la generacion d numero de pesos, numeor de filas (caracteristicas) y numero de neuronas (filas)

In [39]:
b = tf.Variable(tf.ones([neuronas]))

In [40]:
multi = tf.matmul(x,w) #multiplicacion de matrices

In [41]:
z = tf.add(multi,b)

In [42]:
activation=tf.sigmoid(z)

In [43]:
inicializacion = tf.global_variables_initializer()

In [44]:
valores_x = np.random.random([1,caracteristicas])

In [45]:
valores_x

array([[0.24682392, 0.47808479, 0.88393075, 0.84711397, 0.76329891,
        0.18887693, 0.99377279, 0.46056864, 0.86845047, 0.41356612]])

In [47]:
with tf.Session() as sesion:
    sesion.run(inicializacion)
    resultado = sesion.run(activation,feed_dict={x:valores_x})

In [48]:
resultado

array([[0.94886684, 0.12974326, 0.8501938 , 0.83784425]], dtype=float32)