## Varialbles y Placeholders

In [1]:
import tensorflow as tf

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [3]:
tensor = tf.random_uniform((5,5),0,1) #matriz 5x5 de 0 a 1

In [4]:
variable =  tf.Variable(initial_value = tensor)

In [6]:
print(variable) #tensor de tipo variable

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>


In [7]:
inicializador = tf.global_variables_initializer() #inicializador

In [8]:
with tf.Session() as sesion:
    sesion.run(inicializador)
    resultado = sesion.run(variable)

In [10]:
print(resultado)

[[0.23589456 0.3366865  0.36073387 0.63583565 0.18126297]
 [0.81135106 0.47892046 0.88487256 0.89203477 0.24286687]
 [0.12444568 0.89862084 0.32557642 0.98847544 0.7537899 ]
 [0.22440886 0.60456884 0.82579994 0.4591322  0.9523392 ]
 [0.91707253 0.93112755 0.46838188 0.21140265 0.79004335]]


In [11]:
# placeholders son espacios vacios, como una X en una ecuacion
incognito = tf.placeholder(tf.float32,shape=(20,20))

In [12]:
print(incognito)

Tensor("Placeholder:0", shape=(20, 20), dtype=float32)
